### ISSUE TITLE
Pesquisa de uma api que fornece os registros de doenças para implementar no banco de dados

### ISSUE THREAD

**Issue by Marc536** [GuiGa455/Tcc-Manchester#11]

**Comment by Lucas-G-Lopes** [comment]
https://www.malacards.org/card/breast_cancer?search=Breast%20Cancer#clinical_features

http://www.diseasesdatabase.com/item_relationships.asp?glngUserChoice=1598&bytRel=2&blnBW=0&strBB=LR&blnClassSort=255&Key={F00A45D0-AC22-4BB4-85D0-E765CA831AD3}

**Comment by Marc536** [comment]
https://omim.org/
